import { lazy, type LazyExoticComponent, type ComponentType } from 'react';
import type { GameProps } from './types';
import type { AxisWeights } from '../lib/synapse';

export type GameCategory = 'must-have' | 'recommended' | 'innovative';

export type GameDef = {
  id: string;
  /** i18n key for the display name, e.g. games.cube.name */
  nameKey: string;
  /** i18n key for the short tagline */
  taglineKey: string;
  route: string;
  category: GameCategory;
  emoji: string;
  /** Tailwind gradient classes for the card */
  gradient: string;
  /** Playable now? If false, shows as "Coming soon". */
  available: boolean;
  /** Shows the difficulty-select screen (EASY–EXPERT) before launching. */
  hasDifficulty?: boolean;
  /** How this game taps the three Synapse axes (memory / logic / reflex). */
  axes?: AxisWeights;
  component?: LazyExoticComponent<ComponentType<GameProps>>;
};

// The portfolio: 20 playable games across must-have / recommended / innovative
// (Clubhouse Games × NYT Games), with chess still teasing the roadmap. Each game
// carries Synapse axis weights (memory / logic / reflex). Order follows the doc.
export const GAMES: GameDef[] = [
  {
    id: 'cube',
    nameKey: 'games.cube.name',
    taglineKey: 'games.cube.tagline',
    route: '/play/cube',
    category: 'must-have',
    emoji: '🧊',
    gradient: 'from-[#ff3b30] via-[#ffd60a] to-[#34c759]',
    available: true,
    axes: { memory: 0.3, logic: 0.4, reflex: 0.3 },
    component: lazy(() => import('./cube/CubeGame')),
  },
  {
    id: 'sudoku',
    nameKey: 'games.sudoku.name',
    taglineKey: 'games.sudoku.tagline',
    route: '/play/sudoku',
    category: 'must-have',
    emoji: '🔢',
    gradient: 'from-sky-500 to-indigo-600',
    available: true,
    hasDifficulty: true,
    axes: { logic: 0.8, memory: 0.2 },
    component: lazy(() => import('./sudoku/SudokuGame')),
  },
  {
    id: 'wordle',
    nameKey: 'games.wordle.name',
    taglineKey: 'games.wordle.tagline',
    route: '/play/wordle',
    category: 'must-have',
    emoji: '🟩',
    gradient: 'from-emerald-500 to-teal-600',
    available: true,
    hasDifficulty: true,
    axes: { memory: 0.4, logic: 0.5, reflex: 0.1 },
    component: lazy(() => import('./wordle/WordleGame')),
  },
  {
    id: 'solitaire',
    nameKey: 'games.solitaire.name',
    taglineKey: 'games.solitaire.tagline',
    route: '/play/solitaire',
    category: 'must-have',
    emoji: '🃏',
    gradient: 'from-rose-500 to-red-600',
    available: true,
    hasDifficulty: true,
    axes: { logic: 0.5, memory: 0.3, reflex: 0.2 },
    component: lazy(() => import('./solitaire/SolitaireGame')),
  },
  {
    id: 'watersort',
    nameKey: 'games.watersort.name',
    taglineKey: 'games.watersort.tagline',
    route: '/play/watersort',
    category: 'must-have',
    emoji: '🧪',
    gradient: 'from-cyan-500 to-blue-600',
    available: true,
    hasDifficulty: true,
    axes: { logic: 0.7, memory: 0.3 },
    component: lazy(() => import('./watersort/WaterSortGame')),
  },
  {
    id: 'gomoku',
    nameKey: 'games.gomoku.name',
    taglineKey: 'games.gomoku.tagline',
    route: '/play/gomoku',
    category: 'must-have',
    emoji: '⚫',
    gradient: 'from-amber-500 to-orange-600',
    available: true,
    hasDifficulty: true,
    axes: { logic: 0.7, reflex: 0.3 },
    component: lazy(() => import('./gomoku/GomokuGame')),
  },
  {
    id: 'colorclash',
    nameKey: 'games.colorclash.name',
    taglineKey: 'games.colorclash.tagline',
    route: '/play/colorclash',
    category: 'innovative',
    emoji: '🎨',
    gradient: 'from-pink-500 via-violet-500 to-orange-400',
    available: true,
    hasDifficulty: true,
    axes: { reflex: 0.8, logic: 0.2 },
    component: lazy(() => import('./colorclash/ColorClashGame')),
  },
  {
    id: 'reaction',
    nameKey: 'games.reaction.name',
    taglineKey: 'games.reaction.tagline',
    route: '/play/reaction',
    category: 'innovative',
    emoji: '⚡',
    gradient: 'from-lime-400 to-green-600',
    available: true,
    axes: { reflex: 1 },
    component: lazy(() => import('./reaction/ReactionGame')),
  },
  {
    id: 'simon',
    nameKey: 'games.simon.name',
    taglineKey: 'games.simon.tagline',
    route: '/play/simon',
    category: 'innovative',
    emoji: '🎶',
    gradient: 'from-rose-500 to-pink-600',
    available: true,
    axes: { memory: 0.8, reflex: 0.2 },
    component: lazy(() => import('./simon/SimonGame')),
  },
  {
    id: 'memorygrid',
    nameKey: 'games.memorygrid.name',
    taglineKey: 'games.memorygrid.tagline',
    route: '/play/memorygrid',
    category: 'innovative',
    emoji: '🧠',
    gradient: 'from-violet-500 to-fuchsia-600',
    available: true,
    axes: { memory: 1 },
    component: lazy(() => import('./memorygrid/MemoryGridGame')),
  },
  {
    id: 'whack',
    nameKey: 'games.whack.name',
    taglineKey: 'games.whack.tagline',
    route: '/play/whack',
    category: 'innovative',
    emoji: '🐹',
    gradient: 'from-amber-400 to-orange-600',
    available: true,
    axes: { reflex: 1 },
    component: lazy(() => import('./whack/WhackGame')),
  },
  {
    id: 'memory',
    nameKey: 'games.memory.name',
    taglineKey: 'games.memory.tagline',
    route: '/play/memory',
    category: 'recommended',
    emoji: '🃏',
    gradient: 'from-fuchsia-500 to-purple-600',
    available: true,
    hasDifficulty: true,
    axes: { memory: 1 },
    component: lazy(() => import('./memory/MemoryGame')),
  },
  {
    id: 'schulte',
    nameKey: 'games.schulte.name',
    taglineKey: 'games.schulte.tagline',
    route: '/play/schulte',
    category: 'recommended',
    emoji: '🧭',
    gradient: 'from-teal-500 to-cyan-600',
    available: true,
    hasDifficulty: true,
    axes: { reflex: 0.7, logic: 0.3 },
    component: lazy(() => import('./schulte/SchulteGame')),
  },
  {
    id: '2048',
    nameKey: 'games.2048.name',
    taglineKey: 'games.2048.tagline',
    route: '/play/2048',
    category: 'recommended',
    emoji: '🧮',
    gradient: 'from-orange-400 to-red-500',
    available: true,
    axes: { logic: 0.8, memory: 0.2 },
    component: lazy(() => import('./game2048/Game2048')),
  },
  {
    id: 'slide',
    nameKey: 'games.slide.name',
    taglineKey: 'games.slide.tagline',
    route: '/play/slide',
    category: 'recommended',
    emoji: '🔢',
    gradient: 'from-sky-500 to-blue-700',
    available: true,
    hasDifficulty: true,
    axes: { logic: 0.7, memory: 0.3 },
    component: lazy(() => import('./slide/SlideGame')),
  },
  {
    id: 'lightsout',
    nameKey: 'games.lightsout.name',
    taglineKey: 'games.lightsout.tagline',
    route: '/play/lightsout',
    category: 'recommended',
    emoji: '💡',
    gradient: 'from-yellow-400 to-amber-600',
    available: true,
    hasDifficulty: true,
    axes: { logic: 1 },
    component: lazy(() => import('./lightsout/LightsOutGame')),
  },
  {
    id: 'mastermind',
    nameKey: 'games.mastermind.name',
    taglineKey: 'games.mastermind.tagline',
    route: '/play/mastermind',
    category: 'recommended',
    emoji: '🎯',
    gradient: 'from-indigo-500 to-purple-700',
    available: true,
    hasDifficulty: true,
    axes: { logic: 1 },
    component: lazy(() => import('./mastermind/MastermindGame')),
  },
  {
    id: 'minesweeper',
    nameKey: 'games.minesweeper.name',
    taglineKey: 'games.minesweeper.tagline',
    route: '/play/minesweeper',
    category: 'recommended',
    emoji: '💣',
    gradient: 'from-slate-500 to-slate-700',
    available: true,
    hasDifficulty: true,
    axes: { logic: 0.8, memory: 0.2 },
    component: lazy(() => import('./minesweeper/MinesweeperGame')),
  },
  {
    id: 'flood',
    nameKey: 'games.flood.name',
    taglineKey: 'games.flood.tagline',
    route: '/play/flood',
    category: 'recommended',
    emoji: '🌊',
    gradient: 'from-cyan-400 to-blue-600',
    available: true,
    hasDifficulty: true,
    axes: { logic: 0.9, reflex: 0.1 },
    component: lazy(() => import('./flood/FloodGame')),
  },
  {
    id: 'pegsolitaire',
    nameKey: 'games.pegsolitaire.name',
    taglineKey: 'games.pegsolitaire.tagline',
    route: '/play/pegsolitaire',
    category: 'recommended',
    emoji: '🪵',
    gradient: 'from-amber-600 to-yellow-800',
    available: true,
    axes: { logic: 1 },
    component: lazy(() => import('./pegsolitaire/PegSolitaireGame')),
  },
  { id: 'chess', nameKey: 'games.chess.name', taglineKey: 'games.chess.tagline', route: '/play/chess', category: 'recommended', emoji: '♟️', gradient: 'from-slate-500 to-slate-700', available: false },
];

export function getGame(id: string): GameDef | undefined {
  return GAMES.find((g) => g.id === id);
}
